### ISSUE TITLE
members.txt

### ISSUE THREAD

**Issue by garncarz** [mgp4/prague-transport-2017#15]
@jr @pholasek Is it ok to include your email addresses in a versioned file? I hope it is, since your email addresses already identify your commits. I'll shuffle our names randomly to get the list.

**Comment by pholasek** [comment]
No problem.

**Comment by dzejar** [comment]
hmmm, ok

**Comment by garncarz** [comment]
`NAME;EMAIL;\r\n` - LOL, I hope `\n` is enough. (Don't want to google how to save `\r\n` in Vim.)
