### ISSUE TITLE
logo.png

### ISSUE THREAD

**Issue by garncarz** [mgp4/prague-transport-2017#17]
What do we do about this one?

It should be 150 x 150 px.

**Comment by garncarz** [comment]
Btw. I named the team `Příbor`.

**Comment by pholasek** [comment]
Once at the computer, I will draw Sigmund Freud's House as logo.
ne 26. 3. 2017 v 19:25 odesílatel Ondřej Garncarz <notifications@github.com>
napsal:

**Comment by garncarz** [comment]
I'm glad we're following our tradition "the worst team ever".

**Comment by pholasek** [comment]
Any other ideas?
ne 26. 3. 2017 v 19:51 odesílatel Ondřej Garncarz <notifications@github.com>
napsal:

**Comment by garncarz** [comment]
No, do it.

**Comment by pholasek** [comment]
Done, you can find it in repository.

**Comment by garncarz** [comment]
Cool. 😆
