### ISSUE TITLE
Task 2 - scikit-learn?

### ISSUE THREAD

**Issue by garncarz** [mgp4/prague-transport-2017#3]

**Comment by garncarz** [comment]
1. Implement some algorithm in the `task2` directory.
2. Bind it in `task2/api.py`.
3. Adjust tests in `tests/test_task2.py`.

Please try pushing to a branch first to see if tests succeed well.

**Comment by dzejar** [comment]
Estimated Airplane Noise Levels in A-Weighted Decibels by FAA: https://www.faa.gov/documentLibrary/media/Advisory_Circular/AC36-3H%20Chg%201.pdf
