### ISSUE TITLE
Task 1 - C(++) binding

### ISSUE THREAD

**Issue by garncarz** [mgp4/prague-transport-2017#4]

**Comment by pholasek** [comment]
```
struct Offer {
    unsigned int from, to, price;
}

struct Result {
    bool feasibility;
    unsigned int total_cost;
    unsigned int depot_id;
    unsigned int recommended_offers_num;
    struct Offer *recommended_offers;
}

struct Result find_hub(int cities_count, int int offers_count, struct Offer *offers);
```

**Comment by garncarz** [comment]
@pholasek Please move source files for Task 1 into the `task1` directory, we're instructed to do so.

**Comment by pholasek** [comment]
no jo
st 22. 3. 2017 v 18:57 odesílatel Ondřej Garncarz <notifications@github.com>
napsal:

**Comment by garncarz** [comment]
It seems there are 3 main possibilities:
1. https://docs.python.org/3/extending/extending.html
2. http://cython.org/
3. having a standalone C(++) program and communicating with it through stdin/stderr

The 1st & 2nd one seem actually more complicated than I thought it would be.
On the other hand, the 3rd one should provide a more robust solution (memory leak from the C code would result in 1 exception, it wouldn't take the whole Python application down), although not that seamless. (We would communicate with it in a "KSP" style, I guess.)

**Comment by pholasek** [comment]
I vote for #3, let's KISS.

**Comment by garncarz** [comment]
Ok, *nothin' to lose* that way. But I'll look into it *tomorrow* when *crazy nights* are over.

**Comment by garncarz** [comment]
So your program can expect this in stdin (same data as in the example):
```
4
0 1 6
1 2 10
2 1 10
1 3 12
3 2 8
3 0 1
```

This output is expected then:
```
1 15 3
0 1 6
3 0 1
3 2 8
```

(The fist `1` meaning `True`. Maybe there could be also count of recommended offers, but I guess I can do without it.)

**Comment by pholasek** [comment]
Works for this input.

**Comment by garncarz** [comment]
Good, please try more inputs. But this issue is about binding, so I've got to reopen this, it's still not finished on my part. 😄

**Comment by pholasek** [comment]
Ok, do you need anything else from my side @garncarz ? Stdin-stdout is working.

**Comment by garncarz** [comment]
@pholasek 

```
$ task1/find_hub
4
    0 1 6
    1 2 10
    2 1 10
    1 3 12
    3 2 8
    3 0 1
```

does nothing. No CPU usage. It's stuck.

**Comment by pholasek** [comment]
It is waiting on stdin -
```
cat simple_in.txt | ./find_hub
1 15 3
3 0 1
0 1 6
3 2 8
```

**Comment by garncarz** [comment]
Hmm, probably just a case of C++ not being able to ignore whitespaces.
