### ISSUE TITLE
Task 1 - C(++) algorithm

### ISSUE THREAD

**Issue by pholasek** [mgp4/prague-transport-2017#9]
Current implementation of Edmond's algorithm doesn't give proper solution, i.e. returns edges that doesn't exist. Hopefully, it is not because the graph is sparse.

**Comment by garncarz** [comment]
How to reproduce this? Please provide a complete example (stdin, stdout).

**Comment by pholasek** [comment]
```
cat simple_in.txt | ./find_hub

1 0 2147483647
0 3 0
3 1 0
0 2 0
```
but output should be
```
1 15 3
0 1 6
3 0 1
3 2 8
```
```

**Comment by pholasek** [comment]
Working well after some tweaking, I am going to add some bigger speed tests.

**Comment by pholasek** [comment]
- 10 cities, 10k lines - 0.04s
- 100 cities, 100k lines - 6.175s
- 1000 cities, 1M lines - didn't finished within 15 minutes

**Comment by garncarz** [comment]
@pholasek If it's somehow automated, maybe push that testing script to the code.
